### ISSUE TITLE
Site unloads itself :(

### ISSUE THREAD

**Issue by Zexyp** [marekvospel/vospel.cz#104]
After loading your site it goes blank (but briefly flashes with content)...
I guess it's broken...
Happy fixing!

Browser: Firefox 133.0.3

**Comment by marekvospel** [comment]
Thanks for the report!On Dec 12, 2024 1:32 AM, Pjavel ***@***.***> wrote:
After loading your site it goes blank (but briefly flashes with content)...
I guess it's broken...
Happy fixing!
Browser: Firefox 133.0.3

**Comment by marekvospel** [comment]
The issue seemed to be a version conflict. (caused by an automatic update by rennovate - I guess it doesn't really make sense for small SPA without automated tests)

Could you please verify this from your device?
